name: cicdpipleine

on:
  pull_request:
    branches: ["main"]

  push:
    branches: ["main"]

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}

  BACKEND_IMAGE: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/userapp-backend
  FRONTEND_IMAGE: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/userapp-frontend

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Backend tests
        working-directory: backend
        run: |
          npm install
          npm test || true

      - name: Frontend tests
        working-directory: frontend
        run: |
          npm install
          npm test -- --watchAll=false || true

      - name: Trivy Scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          scan-ref: .

  build-and-push:
    needs: test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Configure AWS
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Login to ECR
      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION | \
          docker login --username AWS --password-stdin \
          $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

      # Build backend
      - name: Build backend image
        run: |
          docker build -t $BACKEND_IMAGE:${{ github.sha }} ./backend
          docker tag $BACKEND_IMAGE:${{ github.sha }} $BACKEND_IMAGE:latest

      # Build frontend
      - name: Build frontend image
        run: |
          docker build -t $FRONTEND_IMAGE:${{ github.sha }} ./frontend
          docker tag $FRONTEND_IMAGE:${{ github.sha }} $FRONTEND_IMAGE:latest

      # Push backend
      - name: Push backend image
        run: |
          docker push $BACKEND_IMAGE:${{ github.sha }}
          docker push $BACKEND_IMAGE:latest

      # Push frontend
      - name: Push frontend image
        run: |
          docker push $FRONTEND_IMAGE:${{ github.sha }}
          docker push $FRONTEND_IMAGE:latest

  deploy-staging:
    needs: build-and-push
    runs-on: ubuntu-latest
    environment:
      name: staging

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy via SSM
        run: |
          aws ssm send-command \
          --instance-ids ${{ secrets.EC2_INSTANCE_ID }} \
          --document-name "AWS-RunShellScript" \
          --parameters 'commands=[
            "cd /var/snap/amazon-ssm-agent/13349/User-app",
            "aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin '"$AWS_ACCOUNT_ID"'.dkr.ecr.ap-south-1.amazonaws.com",
            "docker compose down --remove-orphans",
            "docker compose pull",
            "docker compose up -d --force-recreate --pull always"
          ]'


  deploy-production:
    needs: deploy-staging
    runs-on: ubuntu-latest
    environment:
      name: production   # manual approval enabled in GitHub

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy Production via SSM
        run: |
          aws ssm send-command \
          --instance-ids ${{ secrets.EC2_INSTANCE_ID }} \
          --document-name "AWS-RunShellScript" \
          --parameters 'commands=[
            "cd /home/ssm-user/User-app",
            "aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin '"$AWS_ACCOUNT_ID"'.dkr.ecr.ap-south-1.amazonaws.com",
            "docker compose pull",
            "docker compose down",
            "docker compose up -d"
          ]'

  notify:
    if: failure()
    needs: [deploy-production]
    runs-on: ubuntu-latest

    steps:
      - name: Slack alert
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{"text":"🚨 CI/CD Pipeline Failed for User App (ECR + SSM)"}' \
          ${{ secrets.SLACK_WEBHOOK_URL }}
